#! /bin/bash
Docker push shakthiw/casm:latest
Docker push shakthiw/cqc:latest
Docker push shakthiw/cqp:latest
Docker push shakthiw/sqem:latest
Docker push shakthiw/svm:latest
Docker push shakthiw/cre:latest
Docker push shakthiw/csi:latest
Docker push shakthiw/cqg:latest
Docker push shakthiw/acoca:latest
Docker push shakthiw/cpree:latest
Docker push shakthiw/reactive-agent:latest
Docker push shakthiw/service-simulator:latest