version: "3.1"
services:
    casm:
        image: coaas/casm:latest
        container_name: "casm"
        ports:
          - "8070:8080"
          - "4838:4848"
          - "8171:8181"
        environment:
            - CQE_BROKER=cqe
        links:
            - cqc:cqc
            - svm:svm
        depends_on:
            - svm
            - cqc

    cre:
        image: coaas/cre:latest
        container_name: "cre"
        ports:
          - "8583"
          - "8008:8008"
        restart: always

    graphhopper:
      container_name: "graphhopper"
      image: israelhikingmap/graphhopper:latest
      ports:
        - "8989:8989"

    svm:
        image: coaas/svm:latest
        container_name: "svm"
        ports:
          - "9191"
          - "8004:8004"
        restart: always
        links:
            - fuseki:fuseki
        depends_on:
            - fuseki

    csi:
        image: coaas/csi:latest
        container_name: "csi"
        ports:
          - "8582"
          - "8002:8002"
        restart: always
        links:
            - postgres:postgres
            - sqem:sqem
        depends_on:
            - postgres
            - sqem


    cqp:
        image: coaas/cqp:latest
        container_name: "cqp"
        ports:
          - "8585"
          - "8007:8007"
        restart: always


    cqc:
        image: coaas/cqc:latest
        container_name: "cqc"
        ports:
          - "8484"
          - "8001:8001"
        restart: always
        links:
            - cqp:cqp
            - sqem:sqem
            - csi:csi
        depends_on:
            - cqp
            - sqem
            - csi

    sqem:
        image: coaas/sqem:latest
        container_name: "sqem"
        ports:
          - "8686"
          - "8003:8003"
        restart: always
        depends_on:
          - mongodb
        links:
          - mongodb

#    grafana:
#        image: grafana/grafana:5.1.0
#        expose:
#          - "3000"
#        ports:
#          - "3000:3000"
#        environment:
#          - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
#        user: "104"
#        network_mode: "bridge"
#
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER=alex
          - MONGODB_PASS=contextstorage_17
        volumes:
          #for mac
          - ./data/db:/data/db
          #for windows
          #- /userlogin/pgdata:/var/lib/postgresql/data
        ports:
            - 27017:27017
        command: mongod --logpath=/dev/null # --quiet

    mongo-seed:
        build: ./mongo-seed
        restart: on-failure
        depends_on:
          - mongodb
        links:
          - mongodb

    fuseki:
        container_name: fuseki
        image: stain/jena-fuseki
        environment:
          - ADMIN_PASSWORD=admin
          - JVM_ARGS=-Xmx2g
        ports:
         - 27018:3030
        volumes:
         - ./data/jena:/data/jena
#         - /userlogin/jena:/var/lib/jena/data

    postgres:
        image: postgres:9.6.1
        container_name: "postgres"
        environment:
          - POSTGRES_USER=coaas
          - POSTGRES_PASSWORD=PostCoaaS2020
          - POSTGRES_DB=coaas
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./pgdata:/var/lib/postgresql/data
          #for windows
          #- /userlogin/pgdata:/var/lib/postgresql/data
        ports:
            - 5433:5432