import {processService} from "../connect/actions";

export const FETCH_SERVICE_REQUEST = "SERVICE/FETCH_SERVICE_REQUEST";
export const FETCH_SERVICE_SUCCESS = "SERVICE/FETCH_SERVICE_SUCCESS";
export const FETCH_SERVICE_FAILURE = "SERVICE/FETCH_SERVICE_FAILURE";

export const FETCH_GRAPHS_REQUEST = "SERVICE/FETCH_GRAPHS_REQUEST";
export const FETCH_GRAPHS_SUCCESS = "SERVICE/FETCH_GRAPHS_SUCCESS";
export const FETCH_GRAPHS_FAILURE = "SERVICE/FETCH_GRAPHS_FAILURE";

export const FETCH_CLASSES_REQUEST = "SERVICE/FETCH_CLASSES_REQUEST";
export const FETCH_CLASSES_SUCCESS = "SERVICE/FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_FAILURE = "SERVICE/FETCH_CLASSES_FAILURE";

export const FETCH_TERMS_REQUEST = "SERVICE/FETCH_TERMS_REQUEST";
export const FETCH_TERMS_SUCCESS = "SERVICE/FETCH_TERMS_SUCCESS";
export const FETCH_TERMS_FAILURE = "SERVICE/FETCH_TERMS_FAILURE";

export const REGISTER_SERVICE_REQUEST = "SERVICE/REGISTER_SERVICE_REQUEST";
export const REGISTER_SERVICE_SUCCESS = "SERVICE/REGISTER_SERVICE_SUCCESS";
export const REGISTER_SERVICE_FAILURE = "SERVICE/REGISTER_SERVICE_FAILURE";


export const PROCESS_SERVICE_REQUEST = "SERVICE/PROCESS_SERVICE_REQUEST";

export const SENDING_REQUEST = "SERVICE/SENDING_REQUEST";