export const FETCH_SERVICES_REQUEST = "TOOLBAR/FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_SUCCESS = "TOOLBAR/FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAILURE = "TOOLBAR/FETCH_SERVICES_FAILURE";

export const FETCH_ENTITIES_REQUEST = "TOOLBAR/FETCH_ENTITIES_REQUEST";
export const FETCH_ENTITIES_SUCCESS = "TOOLBAR/FETCH_ENTITIES_SUCCESS";
export const FETCH_ENTITIES_FAILURE = "TOOLBAR/FETCH_ENTITIES_FAILURE";

export const FETCH_SITUATIONS_REQUEST = "TOOLBAR/FETCH_SITUATIONS_REQUEST";
export const FETCH_SITUATIONS_SUCCESS = "TOOLBAR/FETCH_SITUATIONS_SUCCESS";
export const FETCH_SITUATIONS_FAILURE = "TOOLBAR/FETCH_SITUATIONS_FAILURE";

export const FETCH_SUBS_REQUEST = "TOOLBAR/FETCH_SUBS_REQUEST";
export const FETCH_SUBS_SUCCESS = "TOOLBAR/FETCH_SUBS_SUCCESS";
export const FETCH_SUBS_FAILURE = "TOOLBAR/FETCH_SUBS_FAILURE";


export const SENDING_REQUEST = "TOOLBAR/SENDING_REQUEST";