export const CONNECT_REQUEST = "CONNECT/CONNECT_REQUEST";
export const CONNECT_SUCCESS = "CONNECT/CONNECT_SUCCESS";
export const CONNECT_FAILURE = "CONNECT/CONNECT_FAILURE";

export const DISCONNECT_REQUEST = "CONNECT/DISCONNECT_REQUEST";

export const SENDING_REQUEST = "CONNECT/SENDING_REQUEST"